version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: sunlax-nginx
    ports:
      - "80:80"
    volumes:
      - ../../App/:/data/wwwroot/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./log/:/data/logs/:rw
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-php
  golang:
    image: golang:latest
    ports:
      - "8080:8080"
    container_name: sunlax-golang
    networks:
      - net-mysql
      - net-redis
    volumes:
      - ../../GOAPP/src:/go/src:rw
    restart: always
    tty: true

  php:
    build:
      context: ./php
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        XDEBUG_VERSION: 2.6.1
        SWOOLE_VERSION: 4.2.1
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - ../../App/:/data/wwwroot/:rw
      - ./conf/php/php.ini:/usr/local/php/etc/php.ini:ro
      - ./conf/php/php-fpm.conf:/usr/local/php/etc/php-fpm.d/www.conf:rw
      - ./log/:/data/logs/:rw
    restart: always
    container_name: sunlax-php
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:5.7
    container_name: sunlax-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/mysql.cnf:/usr/local/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    restart: always
    container_name: sunlax-redis
    networks:
      - net-redis
    ports:
      - "6379:6379"

networks:
  net-php:
  net-mysql:
  net-redis: